#ifndef IPC_MAIL_LIST_H_
#define IPC_MAIL_LIST_H_

#define IPC_PRIVATE_MAIL_LIST \

#define IPC_SUBSCRIBABLE_MAIL_LIST \

#define IPC_RETRIEVE_TOUT_MS (500U)

#undef IPC_MAIL
#define IPC_MAIL(mail, description) mail,

#define PRIVATE_MAIL(mail, desc)      IPC_MAIL(mail, desc)
#define SUBSCRIBABLE_MAIL(mail, desc) IPC_MAIL(mail, desc)

enum
{
   IPC_BEGIN_PRIVATE_MAIL_LIST_ID = 0,
   IPC_PRIVATE_MAIL_LIST
   IPC_END_PRIVATE_MAIL_LIST_ID,
   IPC_BEGIN_SUBSCRIBABLE_MAIL_LIST_ID = IPC_END_PRIVATE_MAIL_LIST_ID,
   IPC_SUBSCRIBABLE_MAIL_LIST
   IPC_END_SUBSCRIBABLE_MAIL_LIST_ID,
   IPC_TOTAL_MAIL_LIST_ITEMS
};
#endif /*IPC_MAIL_LIST_H_*/
